name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  compile_job:
    name: OpenEdge Compile job
    image: ec2-54-80-142-101.compute-1.amazonaws.com:9443/openedge:12.8.0
    
    
