name: OpenEdgeOps
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  compile:
    name: OpenEdge Compile job
    runs-on: ubuntu-latest
    container: ec2-54-80-142-101.compute-1.amazonaws.com:9443/openedge-4gl:12.8.0
    steps:
      - uses: actions/checkout@v2
  
    
